name = "GrowthMaps"
uuid = "a252ced4-3752-11e9-0615-256422162c4d"
authors = ["Rafael Schouten", "James Maino"]
version = "0.2.6"

[deps]
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
InteractModels = "546b680c-e627-4c75-86f8-7ef2c81e5d51"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
ModelParameters = "4744a3fa-6c31-4707-899e-a3298e4618ad"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulRecipes = "42071c24-d89e-48dd-8a24-8a12d9b8861f"

[compat]
ConstructionBase = "1"
InteractModels = "0.4"
LsqFit = "0.10, 0.11, 0.12"
ModelParameters = "0.3"
Plots = "1"
Rasters = "0.1"
Reexport = "0.2, 1.0"
Unitful = "1"
UnitfulRecipes = "1"
julia = "1"

[extras]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ArchGDAL", "HDF5", "Pkg", "StaticArrays", "Test"]
